[package]
name = "arangodb"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
arangodb-http = { path = "../arangodb-http" }
error-chain = "0.12.0"